### ISSUE TITLE
求支持N1

### ISSUE THREAD

**Issue by cjlhll** [wukongdaily/AutoBuildImmortalWrt#3]
如题。

**Comment by wukongdaily** [comment]
你好。N1这款电视盒子应该发售5、6年了吧。但是openwrt一直没支持对吧。所以我觉得openwrt可能认为这属于电视盒子范畴 就不适配了。应该是所有电视盒子芯片amlogic的 都没得到官方支持吧。而imm固件也是根据原版openwrt来同步的，基本上原版openwrt不支持，我觉得后续imm支持的可能性就很小很小了。（以上是我的分析。）而我们作为普通用户，仅仅是调用人家的工具而已啦。。
所以N1只能用其他系统了。

**Comment by cjlhll** [comment]
> 你好。N1这款电视盒子应该发售5、6年了吧。但是openwrt一直没支持对吧。所以我觉得openwrt可能认为这属于电视盒子范畴 就不适配了。应该是所有电视盒子芯片amlogic的 都没得到官方支持吧。而imm固件也是根据原版openwrt来同步的，基本上原版openwrt不支持，我觉得后续imm支持的可能性就很小很小了。（以上是我的分析。）而我们作为普通用户，仅仅是调用人家的工具而已啦。。
> 
> 所以N1只能用其他系统了。
> 
> 

好的。感谢回复，x86在路上了
